doors:
  main:
    pretty: Front
  2:
    pretty: Garasje
  3:
    pretty: Verksted

gates:
  main:
    pretty: Garasje

mqtt:
  broker_url: 192.168.0.1
  broker_port: 1883
  username: user
  password: passs
  client_id: doorbell
  qos: 0
  ssl: False